apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: nvidia-wsl-gpu
spec:
  rules:
    - name: dxgkrnl-module
      labels:
        dxgkrnl: "true"
        pci-10de.present: "true"
      matchFeatures:
        - feature: kernel.enabledmodule
          matchExpressions:
            "dxgkrnl":
              op: Exists
