user:
  account: orchestrator:2000:2000:bash
  editor: nano

ssh:
  key:
    name: id_orchestrator
  export:
    enabled: true
    alias: orchestrator

podman:
  export:
    enabled: true

rke2:
  version: v1.37
  gpu_operator_version: v26.7.0
  kubeconfig_sync: true
